id = "hone"
name = "Hone"
description = "Hone programming language support"
version = "0.0.1"
schema_version = 1
authors = ["Jak Boulton <jak.boulton@gmail.com>"]
repository = "https://github.com/Secticide/hone"

[grammars.hone]
repository = "https://github.com/Secticide/tree-sitter-hone"
commit = "53c0615af9615b62cb55846a20a0807e2b6462fc"
